/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domain.Trener;
import form.model.ModelTabeleUlogovani;
import controller.Controller;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import server.Server;

/**
 *
 * @author milaz
 */
public class FormaServer extends javax.swing.JFrame {

    private Server server;

    /**
     * Creates new form FormaServer
     */
    public FormaServer() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        srediTabelu();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JTextField();
        btnPokreni = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUlogovani = new javax.swing.JTable();
        btnDbConfig = new javax.swing.JButton();
        jlbProgramName = new javax.swing.JLabel();
        jlbStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Status:");

        lblStatus.setEnabled(false);
        lblStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblStatusActionPerformed(evt);
            }
        });

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ulogovani korisnici"));

        tabelaUlogovani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUlogovani);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnDbConfig.setText("Konfiguracija konekcije");
        btnDbConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDbConfigActionPerformed(evt);
            }
        });

        jlbProgramName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbProgramName.setText("SOFTVERSKI SISTEM SPORTSKOG KLUBA");

        jlbStudent.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jlbStudent.setText("SARA ŠPANOVIĆ 2019/0196");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbProgramName)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jlbStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(btnDbConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbProgramName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnPokreni)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnDbConfig)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>                        

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {                                           
         if(server == null) {
            server = new Server(this);
            server.start();
            lblStatus.setText("Pokrenuto");
            lblStatus.setForeground(Color.green);
            btnPokreni.setText("Ugasi");
            btnDbConfig.setEnabled(false);
        } else {
            try {
                server.zaustaviServer();
                server = null;
                lblStatus.setText("Ugaseno");
                lblStatus.setForeground(Color.red);
                btnPokreni.setText("Pokreni");
                btnDbConfig.setEnabled(true);
            } catch ( IOException ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom gasenja servera", "", JOptionPane.ERROR_MESSAGE);
                
            } catch (SQLException ex) {
              JOptionPane.showMessageDialog(this, "Greska prilikom gasenja servera", "", JOptionPane.ERROR_MESSAGE);
            }
        }

    }                                          

    private void btnDbConfigActionPerformed(java.awt.event.ActionEvent evt) {                                            
       if(this.server == null) {
           try {
               (new FrmDbConfig(this, false)).setVisible(true);
           } catch (IOException ex) {
               Logger.getLogger(FormaServer.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }                                           

    private void lblStatusActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

  

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDbConfig;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbProgramName;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JTextField lblStatus;
    private javax.swing.JTable tabelaUlogovani;
    // End of variables declaration                   

    

    public void srediTabelu() {
        tabelaUlogovani.setModel(new ModelTabeleUlogovani(new ArrayList<>()));
         lblStatus.setText("Ugaseno");
        lblStatus.setForeground(Color.red);
    }
    
    public void osveziListu(){
        tabelaUlogovani.setModel(new ModelTabeleUlogovani(server.getUlogovaneTrenere()));
    }

   

}
