
package form;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Properties;
import javax.swing.JOptionPane;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 *
 * @author Sara
 */
public class FrmDbConfig extends javax.swing.JDialog {
	//Properties properties = new Properties();
    /**
     * Creates new form FrmDbConfig
     */
	private DBConfigModel dbConfigModel;
	
    public FrmDbConfig(java.awt.Frame parent, boolean modal) throws FileNotFoundException, IOException {
        super(parent, modal);
        initComponents();
       setLocationRelativeTo(null);
       /*
            properties.load(new FileInputStream("config/dbconfig.properties"));
            popuniPolja();
            */
       
       String txtJson = new String(Files.readAllBytes(Paths.get("dbconfigJson.txt")));
       ObjectMapper objectMapper = new ObjectMapper();
       dbConfigModel = objectMapper.readValue(txtJson, DBConfigModel.class);
       popuniPolja();
    }
    
    private void popuniPolja() throws FileNotFoundException, IOException
    {
        /*
            String url = properties.getProperty("url");
            String username = properties.getProperty("username");
            String password = properties.getProperty("password");
        poljeUrl.setText(url);
        poljeKorisnickoIme.setText(username);
        poljeSifra.setText(password);
        */
    	
    	poljeUrl.setText(dbConfigModel.getUrl());
    	poljeKorisnickoIme.setText(dbConfigModel.getUsername());
    	poljeSifra.setText(dbConfigModel.getPassword());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        poljeUrl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        poljeKorisnickoIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        poljeSifra = new javax.swing.JTextField();
        btnSacuvajIzmene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Konfiguracija baze podataka");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("URL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Korisnicko ime");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Sifra");

        btnSacuvajIzmene.setText("Sacuvaj izmene");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poljeUrl)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addComponent(poljeKorisnickoIme)
                    .addComponent(poljeSifra)
                    .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poljeUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(poljeKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poljeSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajIzmene)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {
            /*properties.setProperty("url", poljeUrl.getText().trim());
            properties.setProperty("username", poljeKorisnickoIme.getText().trim());
            properties.setProperty("password", poljeSifra.getText().trim());
            JOptionPane.showMessageDialog(this, "Sistem je sacuvao promene");
            */
        	
        	dbConfigModel.setUrl(poljeUrl.getText().trim());
        	dbConfigModel.setPassword(poljeSifra.getText().trim());
        	dbConfigModel.setUsername(poljeKorisnickoIme.getText().trim());
        	
        	ObjectMapper objectMapper = new ObjectMapper();
        	
        	BufferedWriter bufferedWriter =Files.newBufferedWriter(Paths.get("dbconfigJson.txt"), StandardOpenOption.TRUNCATE_EXISTING);
        	bufferedWriter.write(objectMapper.writeValueAsString(dbConfigModel));
        	bufferedWriter.flush();
        	bufferedWriter.close();
        	
        	JOptionPane.showMessageDialog(btnSacuvajIzmene, "Uspesno ste izmenili konfiguraciju");
        	this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva promene", "", JOptionPane.ERROR_MESSAGE);
            
        }
    }                                                

   

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField poljeKorisnickoIme;
    private javax.swing.JTextField poljeSifra;
    private javax.swing.JTextField poljeUrl;
    // End of variables declaration                   
}
