package communication;
import java.io.Serializable;

public enum Operation implements Serializable{

	LOGIN,
    DODAJ_CLANA,
    PRETRAZI_CLANA,
    OBRISI_CLANA,
    IZMENI_CLANA,
    VRATI_SVE_CLANOVE,
    DODAJ_OBROK,
    IZMENI_OBROK,
    VRATI_SVE_OBROKE,
    VRATI_SVE_VEZBE,
    DODAJ_PLAN_ISHRANE,
    IZMENI_PLAN_ISHRANE,
    VRATI_SVE_PLANOVE_ISHRANE,
    DODAJ_ISHRANU,
    IZMENI_ISHRANU,
    VRATI_SVE_ISHRANE,
    DODAJ_PLAN_TRENINGA,
    IZMENI_PLAN_TRENINGA,
    VRATI_SVE_PLANOVE_TRENINGA,
    DODAJ_TRENING,
    IZMENI_TRENING,
    VRATI_SVE_TRENINGE,
    VRATI_SVE_TRENERE
}
